<#macro main>

<form method="post" enctype="application/x-www-form-urlencoded">
    <div class="row" class="pt-1">
        <div class="d-flex align-items-center flex-column link-secondary lh-1">
            Stuck or changed your mind? <#-- I would like to t -->
            <button type="submit" class="btn btn-link p-0 ps-1" id="skipped" name="skipped" value="">
                Use a different enrollment method
            </button>
        </div>
    </div>
</form> 

</#macro>
